# Generated by Django 2.2.17 on 2021-01-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pickture',
            new_name='picture',
        ),
    ]
